version: '3'

services:
  backend:
    image: lemraus/news-app-backend:latest
    container_name: news-app-backend
    expose: 
      - 5000
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_DEBUG=0

  frontend:
    image: lemraus/news-app-frontend:latest
    container_name: news-app-frontend
    expose: 
      - 3000

  nginx:
    image: lemraus/news-app-nginx:latest
    container_name: news-app-nginx
    expose:
      - 80
    ports:
      - ${HOST_PORT}:80
